{
  "small_blind": { "decimal": "0.5" },
  "big_blind": { "decimal": "1" },
  "actions": [
    { "type": "post ante", "amount": { "decimal": "0.125" } },
    { "type": "post ante", "amount": { "decimal": "0.125" } },
    { "type": "post ante", "amount": { "decimal": "0.125" } },
    { "type": "post ante", "amount": { "decimal": "0.125" } },
    { "type": "post ante", "amount": { "decimal": "0.125" } },
    { "type": "post ante", "amount": { "decimal": "0.125" } },
    { "type": "post SB", "amount": { "decimal": "0.5" } },
    { "type": "post BB", "amount": { "decimal": "1" } },
    { "type": "fold", "amount": { "decimal": "0" } },
    { "type": "fold", "amount": { "decimal": "0" } },
    { "type": "fold", "amount": { "decimal": "0" } },
    { "type": "raise", "amount": { "decimal": "1.5" } },
    { "type": "fold", "amount": { "decimal": "0" } },
    { "type": "call", "amount": { "decimal": "1.5" } },
    { "type": "check", "amount": { "decimal": "0" } },
    { "type": "bet", "amount": { "decimal": "2.1" } },
    { "type": "call", "amount": { "decimal": "2.1" } },
    { "type": "check", "amount": { "decimal": "0" } },
    { "type": "check", "amount": { "decimal": "0" } },
    { "type": "check", "amount": { "decimal": "0" } },
    { "type": "bet", "amount": { "decimal": "7" } },
    { "type": "call", "amount": { "decimal": "7" } }
  ],
  "ante": { "decimal": "0.125" },
  "bb_ante": { "decimal": "0" },
  "players": [
    { "decimal": "100.1" },
    { "decimal": "100.1" },
    { "decimal": "100.1" },
    { "decimal": "100.1" },
    { "decimal": "100.1" },
    { "decimal": "100.1" }
  ],
  "current_street": null,
  "current_player": null,
  "total_pot": { "decimal": "24.450" },
  "_blinds_posted": true,
  "winner": null,
  "n_straddle": 0,
  "largest_blind": { "decimal": "1" },
  "n_decimals": 1,
  "player_names": ["SB", "BB", "UTG", "HJ", "CO", "BTN"],
  "n_seats": 6,
  "n_cards": 2,
  "active_seats": [0, 1, 2, 3, 4, 5],
  "button_idx": 0,
  "hero": 0,
  "hands": [
    ["xx", "xx", "xx", "xx"],
    ["Jd", "8d", "xx", "xx"],
    ["xx", "xx", "xx", "xx"],
    ["xx", "xx", "xx", "xx"],
    ["xx", "xx", "xx", "xx"],
    ["Qc", "9h", "xx", "xx"]
  ],
  "board": ["Jc", "7h", "2s", "6s", "Qd"],
  "currency": "",
  "currency_is_after": true
}
