os: windows
language: shell

env:
  global:
    - PYPATH=/c/Python:/c/Python/Scripts
    - PATH=$PYPATH:$PATH

before_install:
  - choco install python3 --params "/InstallDir:C:\python"
  - python -m pip install --upgrade pip
  - pip install pyinstaller

script:
  - pip install ./
  - cd pyinstaller-win
  - pyinstaller hh-creator.spec  --noconfirm
  - cd dist
  - 7z a hh-creator.zip hh-creator

deploy:
  provider: releases
  api_key:
    secure: ATi6dqpNd01sTWBx4k+ZfVMTV7MA06D36G59SNWehh+px2YRSWilqojC+7smz0OzX4bVKATqDhWzmbwu1rFHEJCONI1z2NmGH0OY3nmMT33V2TvfwIB5SBrEH3kOPqh9ufbTJ3Z2u0hiBLV/JLjfWXtsP4kDemaGc4mK0wkl9EGZ+2xq2OvQIgRFrMsfeQbuFc1eaFUZiAN+QXmj8COtMfbychCYt0MqhqrIR7gc2tGvfZXTE89Z17IjAZLun5IeyrzPIGwBzidSLPcANDpFLUzWfpL9jaUamXTOEplSYMvrAj8Fsi/vKOPKhnRRCAGwIUosG9qmCwc0flXaJdJp5DC1t24rnrNTqzEbTW2Iv2qs9P4WP9ayZMid9/0MHZsLvZNaX5ujiN/m5XUVj6q0ZqGTxeIcaH386OTAbQkdsAIx1HUjpGP0MavT/YCNi7LvOGi3e3HX4o8mV3zv2O8nsXWgCFKlCeWYCYp67XoL2W6D5nI16gM6PHBlxhtbDOYc2kwEU7Y11HtXL82db5AKTbcpz3KsKnBw/+pzcSR3cGXrPlLeDdor7I3xq6l1vIphWSjZLRF26th93zOX1TjMjet5Ms4e/AVA3L/fnld5DZ7iexPlUht5B0qsSgajxDFYPL1sAn7VXjlqWRZs6CbsyKcyV3MZeAgARkHYi92cr7Q=
  file: hh-creator.zip
  on:
    repo: truenicoco/hh-creator
  skip_cleanup: 'true'
