name: Package Application with Pyinstaller
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v4
    - name: export requirements
      run: uv pip compile pyproject.toml -o pyinstaller/requirements.txt
    - name: PyInstaller Windows
      uses: ./.github/actions/pyinstaller
      with:
        path: pyinstaller
    - uses: actions/upload-artifact@v4
      with:
        name: hh-creator
        path: pyinstaller/dist/windows
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        files: pyinstaller/dist/windows